# .github/workflows/rtd-pr-preview.yml
name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened
    # Execute this action only on PRs that touch
    # documentation files.
    paths:
      - "docs/**"
      - "styles/**"
      - .readthedocs.yaml
      - .vale.ini
      - Makefile
      - uv.lock

permissions:
  pull-requests: write

jobs:
  documentation-links:
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.6.5"

      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "plone-sphinx-theme"
          single-version: "true"
