name: Build documentation, check links, spelling, grammar, and style
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  # Build pull requests
  pull_request:
    paths:
      - 'docs/**'
      - 'styles/**'
      - '.github/workflows/rtd-pr-preview.yml'
      - '.github/workflows/test.yml'
      - '.readthedocs.yaml'
      - '.vale.ini'
      - 'requirements.txt'
      - 'requirements-docs.txt'

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements-docs.txt'

      - name: Create Python virtual environment
        run: pip install virtualenv

      - name: pip install requirements
        run: pip install -r requirements-docs.txt

      - name: Check for broken links
        run: make linkcheckbroken

      - name: Build HTML documentation
        run: make html

      - name: Run vale
        run: make vale VALEOPTS="--minAlertLevel='warning'"
